"""add is_draft to Project

Revision ID: c3d922d0161a
Revises: 4e5071f034e2
Create Date: 2026-04-18 12:17:05.917080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'c3d922d0161a'
down_revision: Union[str, Sequence[str], None] = '4e5071f034e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('is_draft', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###

    op.execute("UPDATE projects SET is_draft = True")
    op.alter_column('projects', 'is_draft', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'is_draft')
    # ### end Alembic commands ###
